// Generated by the protocol buffer compiler.  DO NOT EDIT!

package retrofit2.converter.protobuf.nano;

@SuppressWarnings("hiding")
public interface PhoneProtos {

  public static final class Phone extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Phone[] _emptyArray;
    public static Phone[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Phone[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string number = 1;
    public java.lang.String number;

    // optional bool voicemail = 2;
    public boolean voicemail;

    public Phone() {
      clear();
    }

    public Phone clear() {
      number = "";
      voicemail = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.number.equals("")) {
        output.writeString(1, this.number);
      }
      if (this.voicemail != false) {
        output.writeBool(2, this.voicemail);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.number.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.number);
      }
      if (this.voicemail != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.voicemail);
      }
      return size;
    }

    @Override
    public Phone mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.number = input.readString();
            break;
          }
          case 16: {
            this.voicemail = input.readBool();
            break;
          }
        }
      }
    }

    public static Phone parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Phone(), data);
    }

    public static Phone parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Phone().mergeFrom(input);
    }
  }
}
