// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/metadata.jvm/src/jvm_metadata.proto

package retrofit2.kotlin.metadata.jvm;

import retrofit2.kotlin.metadata.ProtoBuf;
import retrofit2.kotlin.protobuf.*;

public final class JvmProtoBuf {
  private JvmProtoBuf() {}
  public static void registerAllExtensions(ExtensionRegistryLite registry) {
    registry.add(JvmProtoBuf.methodSignature);
  }
  public interface StringTableTypesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.metadata.jvm.StringTableTypes)
          MessageLiteOrBuilder {

    /**
     * <code>repeated .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record record = 1;</code>
     */
    java.util.List<StringTableTypes.Record>
        getRecordList();

    /**
     * <code>repeated int32 local_name = 5 [packed = true];</code>
     *
     * <pre>
     * Indices of strings which are names of local classes or anonymous objects
     * </pre>
     */
    java.util.List<Integer> getLocalNameList();
  }
  /**
   * Protobuf type {@code org.jetbrains.kotlin.metadata.jvm.StringTableTypes}
   */
  public static final class StringTableTypes extends
          GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.metadata.jvm.StringTableTypes)
      StringTableTypesOrBuilder {
    // Use StringTableTypes.newBuilder() to construct.
    private StringTableTypes(GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    @SuppressWarnings("UnusedVariable")
    private StringTableTypes(boolean noInit) {
      this.unknownFields = ByteString.EMPTY;}

    private static final StringTableTypes defaultInstance;
    public static StringTableTypes getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public StringTableTypes getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final ByteString unknownFields;
    private StringTableTypes(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      ByteString.Output unknownFieldsOutput =
          ByteString.newOutput();
      CodedOutputStream unknownFieldsCodedOutput =
          CodedOutputStream.newInstance(
              unknownFieldsOutput, 1);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                record_ = new java.util.ArrayList<Record>();
                mutable_bitField0_ |= 0x00000001;
              }
              record_.add(input.readMessage(Record.PARSER, extensionRegistry));
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                localName_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              localName_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                localName_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                localName_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          record_ = java.util.Collections.unmodifiableList(record_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          localName_ = java.util.Collections.unmodifiableList(localName_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }

    public static Parser<StringTableTypes> PARSER =
        new AbstractParser<StringTableTypes>() {

          @Override
      public StringTableTypes parsePartialFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return new StringTableTypes(input, extensionRegistry);
      }
    };

    @Override
    public Parser<StringTableTypes> getParserForType() {
      return PARSER;
    }

    public interface RecordOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record)
            MessageLiteOrBuilder {

      /**
       * <code>optional int32 range = 1 [default = 1];</code>
       *
       * <pre>
       * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
       * </pre>
       */
      boolean hasRange();
      /**
       * <code>optional int32 range = 1 [default = 1];</code>
       *
       * <pre>
       * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
       * </pre>
       */
      int getRange();

      /**
       * <code>optional int32 predefined_index = 2;</code>
       *
       * <pre>
       * Index of the predefined constant. If this field is present, the associated string is ignored
       * </pre>
       */
      boolean hasPredefinedIndex();
      /**
       * <code>optional int32 predefined_index = 2;</code>
       *
       * <pre>
       * Index of the predefined constant. If this field is present, the associated string is ignored
       * </pre>
       */
      int getPredefinedIndex();

      /**
       * <code>optional string string = 6;</code>
       *
       * <pre>
       * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
       * </pre>
       */
      boolean hasString();
      /**
       * <code>optional string string = 6;</code>
       *
       * <pre>
       * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
       * </pre>
       */
      String getString();
      /**
       * <code>optional string string = 6;</code>
       *
       * <pre>
       * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
       * </pre>
       */
      ByteString
          getStringBytes();

      /**
       * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
       *
       * <pre>
       * Perform a described operation on the string
       * </pre>
       */
      boolean hasOperation();
      /**
       * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
       *
       * <pre>
       * Perform a described operation on the string
       * </pre>
       */
      Record.Operation getOperation();

      /**
       * <code>repeated int32 substring_index = 4 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
       * and the second element as the end index.
       * If an operation is not NONE, it's applied _after_ this substring operation
       * </pre>
       */
      java.util.List<Integer> getSubstringIndexList();
      /**
       * <code>repeated int32 substring_index = 4 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
       * and the second element as the end index.
       * If an operation is not NONE, it's applied _after_ this substring operation
       * </pre>
       */
      int getSubstringIndexCount();
      /**
       * <code>repeated int32 substring_index = 4 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
       * and the second element as the end index.
       * If an operation is not NONE, it's applied _after_ this substring operation
       * </pre>
       */
      int getSubstringIndex(int index);

      /**
       * <code>repeated int32 replace_char = 5 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
       * of the character to replace, and the second element as the code point of the replacement character
       * </pre>
       */
      java.util.List<Integer> getReplaceCharList();
      /**
       * <code>repeated int32 replace_char = 5 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
       * of the character to replace, and the second element as the code point of the replacement character
       * </pre>
       */
      int getReplaceCharCount();
      /**
       * <code>repeated int32 replace_char = 5 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
       * of the character to replace, and the second element as the code point of the replacement character
       * </pre>
       */
      int getReplaceChar(int index);
    }
    /**
     * Protobuf type {@code org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record}
     */
    public static final class Record extends
            GeneratedMessageLite implements
        // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record)
        RecordOrBuilder {
      // Use Record.newBuilder() to construct.
      private Record(GeneratedMessageLite.Builder builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      @SuppressWarnings("UnusedVariable")
      private Record(boolean noInit) { this.unknownFields = ByteString.EMPTY;}

      private static final Record defaultInstance;
      public static Record getDefaultInstance() {
        return defaultInstance;
      }

      @Override
      public Record getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final ByteString unknownFields;
      private Record(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        ByteString.Output unknownFieldsOutput =
            ByteString.newOutput();
        CodedOutputStream unknownFieldsCodedOutput =
            CodedOutputStream.newInstance(
                unknownFieldsOutput, 1);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                range_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                predefinedIndex_ = input.readInt32();
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                Operation value = Operation.valueOf(rawValue);
                if (value == null) {
                  unknownFieldsCodedOutput.writeRawVarint32(tag);
                  unknownFieldsCodedOutput.writeRawVarint32(rawValue);
                } else {
                  bitField0_ |= 0x00000008;
                  operation_ = value;
                }
                break;
              }
              case 32: {
                if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                  substringIndex_ = new java.util.ArrayList<Integer>();
                  mutable_bitField0_ |= 0x00000010;
                }
                substringIndex_.add(input.readInt32());
                break;
              }
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                  substringIndex_ = new java.util.ArrayList<Integer>();
                  mutable_bitField0_ |= 0x00000010;
                }
                while (input.getBytesUntilLimit() > 0) {
                  substringIndex_.add(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
              case 40: {
                if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                  replaceChar_ = new java.util.ArrayList<Integer>();
                  mutable_bitField0_ |= 0x00000020;
                }
                replaceChar_.add(input.readInt32());
                break;
              }
              case 42: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
                  replaceChar_ = new java.util.ArrayList<Integer>();
                  mutable_bitField0_ |= 0x00000020;
                }
                while (input.getBytesUntilLimit() > 0) {
                  replaceChar_.add(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
              case 50: {
                ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                string_ = bs;
                break;
              }
            }
          }
        } catch (InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
            substringIndex_ = java.util.Collections.unmodifiableList(substringIndex_);
          }
          if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
            replaceChar_ = java.util.Collections.unmodifiableList(replaceChar_);
          }
          try {
            unknownFieldsCodedOutput.flush();
          } catch (java.io.IOException e) {
          // Should not happen
          } finally {
            unknownFields = unknownFieldsOutput.toByteString();
          }
          makeExtensionsImmutable();
        }
      }
      public static Parser<Record> PARSER =
          new AbstractParser<Record>() {

            @Override
        public Record parsePartialFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws InvalidProtocolBufferException {
          return new Record(input, extensionRegistry);
        }
      };

      @Override
      public Parser<Record> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation}
       */
      public enum Operation
          implements Internal.EnumLite {
        /**
         * <code>NONE = 0;</code>
         */
        NONE(0, 0),
        /**
         * <code>INTERNAL_TO_CLASS_ID = 1;</code>
         *
         * <pre>
         * replaceAll('$', '.')
         * java/util/Map$Entry -&gt; java/util/Map.Entry;
         * </pre>
         */
        INTERNAL_TO_CLASS_ID(1, 1),
        /**
         * <code>DESC_TO_CLASS_ID = 2;</code>
         *
         * <pre>
         * substring(1, length - 1) and then replaceAll('$', '.')
         * Ljava/util/Map$Entry; -&gt; java/util/Map.Entry
         * </pre>
         */
        DESC_TO_CLASS_ID(2, 2),
        ;

        /**
         * <code>NONE = 0;</code>
         */
        public static final int NONE_VALUE = 0;
        /**
         * <code>INTERNAL_TO_CLASS_ID = 1;</code>
         *
         * <pre>
         * replaceAll('$', '.')
         * java/util/Map$Entry -&gt; java/util/Map.Entry;
         * </pre>
         */
        public static final int INTERNAL_TO_CLASS_ID_VALUE = 1;
        /**
         * <code>DESC_TO_CLASS_ID = 2;</code>
         *
         * <pre>
         * substring(1, length - 1) and then replaceAll('$', '.')
         * Ljava/util/Map$Entry; -&gt; java/util/Map.Entry
         * </pre>
         */
        public static final int DESC_TO_CLASS_ID_VALUE = 2;

        @Override
        public final int getNumber() { return value; }

        public static Operation valueOf(int value) {
          switch (value) {
            case 0: return NONE;
            case 1: return INTERNAL_TO_CLASS_ID;
            case 2: return DESC_TO_CLASS_ID;
            default: return null;
          }
        }

        public static Internal.EnumLiteMap<Operation>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static Internal.EnumLiteMap<Operation>
            internalValueMap =
              new Internal.EnumLiteMap<Operation>() {

                @Override
                public Operation findValueByNumber(int number) {
                  return Operation.valueOf(number);
                }
              };

        private final int value;

        @SuppressWarnings("UnusedVariable")
        private Operation(int index, int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation)
      }

      private int bitField0_;
      public static final int RANGE_FIELD_NUMBER = 1;
      private int range_;
      /**
       * <code>optional int32 range = 1 [default = 1];</code>
       *
       * <pre>
       * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
       * </pre>
       */
      @Override
      public boolean hasRange() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 range = 1 [default = 1];</code>
       *
       * <pre>
       * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
       * </pre>
       */
      @Override
      public int getRange() {
        return range_;
      }

      public static final int PREDEFINED_INDEX_FIELD_NUMBER = 2;
      private int predefinedIndex_;
      /**
       * <code>optional int32 predefined_index = 2;</code>
       *
       * <pre>
       * Index of the predefined constant. If this field is present, the associated string is ignored
       * </pre>
       */
      @Override
      public boolean hasPredefinedIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 predefined_index = 2;</code>
       *
       * <pre>
       * Index of the predefined constant. If this field is present, the associated string is ignored
       * </pre>
       */
      @Override
      public int getPredefinedIndex() {
        return predefinedIndex_;
      }

      public static final int STRING_FIELD_NUMBER = 6;
      private Object string_;
      /**
       * <code>optional string string = 6;</code>
       *
       * <pre>
       * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
       * </pre>
       */
      @Override
      public boolean hasString() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string string = 6;</code>
       *
       * <pre>
       * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
       * </pre>
       */
      @Override
      public String getString() {
        Object ref = string_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          ByteString bs =
              (ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            string_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string string = 6;</code>
       *
       * <pre>
       * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
       * </pre>
       */
      @Override
      public ByteString
          getStringBytes() {
        Object ref = string_;
        if (ref instanceof String) {
          ByteString b =
              ByteString.copyFromUtf8(
                  (String) ref);
          string_ = b;
          return b;
        } else {
          return (ByteString) ref;
        }
      }

      public static final int OPERATION_FIELD_NUMBER = 3;
      private Operation operation_;
      /**
       * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
       *
       * <pre>
       * Perform a described operation on the string
       * </pre>
       */
      @Override
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
       *
       * <pre>
       * Perform a described operation on the string
       * </pre>
       */
      @Override
      public Operation getOperation() {
        return operation_;
      }

      public static final int SUBSTRING_INDEX_FIELD_NUMBER = 4;
      private java.util.List<Integer> substringIndex_;
      /**
       * <code>repeated int32 substring_index = 4 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
       * and the second element as the end index.
       * If an operation is not NONE, it's applied _after_ this substring operation
       * </pre>
       */
      @Override
      public java.util.List<Integer>
          getSubstringIndexList() {
        return substringIndex_;
      }
      /**
       * <code>repeated int32 substring_index = 4 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
       * and the second element as the end index.
       * If an operation is not NONE, it's applied _after_ this substring operation
       * </pre>
       */
      @Override
      public int getSubstringIndexCount() {
        return substringIndex_.size();
      }
      /**
       * <code>repeated int32 substring_index = 4 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
       * and the second element as the end index.
       * If an operation is not NONE, it's applied _after_ this substring operation
       * </pre>
       */
      @Override
      public int getSubstringIndex(int index) {
        return substringIndex_.get(index);
      }
      private int substringIndexMemoizedSerializedSize = -1;

      public static final int REPLACE_CHAR_FIELD_NUMBER = 5;
      private java.util.List<Integer> replaceChar_;
      /**
       * <code>repeated int32 replace_char = 5 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
       * of the character to replace, and the second element as the code point of the replacement character
       * </pre>
       */
      @Override
      public java.util.List<Integer>
          getReplaceCharList() {
        return replaceChar_;
      }
      /**
       * <code>repeated int32 replace_char = 5 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
       * of the character to replace, and the second element as the code point of the replacement character
       * </pre>
       */
      @Override
      public int getReplaceCharCount() {
        return replaceChar_.size();
      }
      /**
       * <code>repeated int32 replace_char = 5 [packed = true];</code>
       *
       * <pre>
       * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
       * of the character to replace, and the second element as the code point of the replacement character
       * </pre>
       */
      @Override
      public int getReplaceChar(int index) {
        return replaceChar_.get(index);
      }
      private int replaceCharMemoizedSerializedSize = -1;

      private void initFields() {
        range_ = 1;
        predefinedIndex_ = 0;
        string_ = "";
        operation_ = Operation.NONE;
        substringIndex_ = java.util.Collections.emptyList();
        replaceChar_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;

      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, range_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, predefinedIndex_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeEnum(3, operation_.getNumber());
        }
        if (getSubstringIndexList().size() > 0) {
          output.writeRawVarint32(34);
          output.writeRawVarint32(substringIndexMemoizedSerializedSize);
        }
        for (int i = 0; i < substringIndex_.size(); i++) {
          output.writeInt32NoTag(substringIndex_.get(i));
        }
        if (getReplaceCharList().size() > 0) {
          output.writeRawVarint32(42);
          output.writeRawVarint32(replaceCharMemoizedSerializedSize);
        }
        for (int i = 0; i < replaceChar_.size(); i++) {
          output.writeInt32NoTag(replaceChar_.get(i));
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(6, getStringBytes());
        }
        output.writeRawBytes(unknownFields);
      }

      private int memoizedSerializedSize = -1;

      @Override
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += CodedOutputStream
            .computeInt32Size(1, range_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += CodedOutputStream
            .computeInt32Size(2, predefinedIndex_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += CodedOutputStream
            .computeEnumSize(3, operation_.getNumber());
        }
        {
          int dataSize = 0;
          for (int i = 0; i < substringIndex_.size(); i++) {
            dataSize += CodedOutputStream
              .computeInt32SizeNoTag(substringIndex_.get(i));
          }
          size += dataSize;
          if (!getSubstringIndexList().isEmpty()) {
            size += 1;
            size += CodedOutputStream
                .computeInt32SizeNoTag(dataSize);
          }
          substringIndexMemoizedSerializedSize = dataSize;
        }
        {
          int dataSize = 0;
          for (int i = 0; i < replaceChar_.size(); i++) {
            dataSize += CodedOutputStream
              .computeInt32SizeNoTag(replaceChar_.get(i));
          }
          size += dataSize;
          if (!getReplaceCharList().isEmpty()) {
            size += 1;
            size += CodedOutputStream
                .computeInt32SizeNoTag(dataSize);
          }
          replaceCharMemoizedSerializedSize = dataSize;
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += CodedOutputStream
            .computeBytesSize(6, getStringBytes());
        }
        size += unknownFields.size();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static Record parseFrom(
          ByteString data)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Record parseFrom(
          ByteString data,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Record parseFrom(byte[] data)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Record parseFrom(
          byte[] data,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Record parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Record parseFrom(
          java.io.InputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static Record parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static Record parseDelimitedFrom(
          java.io.InputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static Record parseFrom(
          CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static Record parseFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(Record prototype) {
        return newBuilder().mergeFrom(prototype);
      }

      @Override
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record}
       */
      public static final class Builder extends
          GeneratedMessageLite.Builder<
            Record, Builder>
          implements
          // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record)
          RecordOrBuilder {
        // Construct using JvmProtoBuf.StringTableTypes.Record.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        @Override
        public Builder clear() {
          super.clear();
          range_ = 1;
          bitField0_ = (bitField0_ & ~0x00000001);
          predefinedIndex_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          string_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          operation_ = Operation.NONE;
          bitField0_ = (bitField0_ & ~0x00000008);
          substringIndex_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          replaceChar_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        @Override
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        @Override
        public Record getDefaultInstanceForType() {
          return Record.getDefaultInstance();
        }

        @Override
        public Record build() {
          Record result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Record buildPartial() {
          Record result = new Record(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.range_ = range_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.predefinedIndex_ = predefinedIndex_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.string_ = string_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.operation_ = operation_;
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            substringIndex_ = java.util.Collections.unmodifiableList(substringIndex_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.substringIndex_ = substringIndex_;
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            replaceChar_ = java.util.Collections.unmodifiableList(replaceChar_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.replaceChar_ = replaceChar_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        @Override
        public Builder mergeFrom(Record other) {
          if (other == Record.getDefaultInstance()) return this;
          if (other.hasRange()) {
            setRange(other.getRange());
          }
          if (other.hasPredefinedIndex()) {
            setPredefinedIndex(other.getPredefinedIndex());
          }
          if (other.hasString()) {
            bitField0_ |= 0x00000004;
            string_ = other.string_;

          }
          if (other.hasOperation()) {
            setOperation(other.getOperation());
          }
          if (!other.substringIndex_.isEmpty()) {
            if (substringIndex_.isEmpty()) {
              substringIndex_ = other.substringIndex_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureSubstringIndexIsMutable();
              substringIndex_.addAll(other.substringIndex_);
            }

          }
          if (!other.replaceChar_.isEmpty()) {
            if (replaceChar_.isEmpty()) {
              replaceChar_ = other.replaceChar_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureReplaceCharIsMutable();
              replaceChar_.addAll(other.replaceChar_);
            }

          }
          setUnknownFields(
              getUnknownFields().concat(other.unknownFields));
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            CodedInputStream input,
            ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Record parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (InvalidProtocolBufferException e) {
            parsedMessage = (Record) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int range_ = 1;
        /**
         * <code>optional int32 range = 1 [default = 1];</code>
         *
         * <pre>
         * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
         * </pre>
         */
        @Override
        public boolean hasRange() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 range = 1 [default = 1];</code>
         *
         * <pre>
         * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
         * </pre>
         */
        @Override
        public int getRange() {
          return range_;
        }
        /**
         * <code>optional int32 range = 1 [default = 1];</code>
         *
         * <pre>
         * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
         * </pre>
         */
        public Builder setRange(int value) {
          bitField0_ |= 0x00000001;
          range_ = value;

          return this;
        }
        /**
         * <code>optional int32 range = 1 [default = 1];</code>
         *
         * <pre>
         * The number of times this record should be repeated; this is used to collapse identical subsequent records in the list
         * </pre>
         */
        public Builder clearRange() {
          bitField0_ = (bitField0_ & ~0x00000001);
          range_ = 1;

          return this;
        }

        private int predefinedIndex_ ;
        /**
         * <code>optional int32 predefined_index = 2;</code>
         *
         * <pre>
         * Index of the predefined constant. If this field is present, the associated string is ignored
         * </pre>
         */
        @Override
        public boolean hasPredefinedIndex() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 predefined_index = 2;</code>
         *
         * <pre>
         * Index of the predefined constant. If this field is present, the associated string is ignored
         * </pre>
         */
        @Override
        public int getPredefinedIndex() {
          return predefinedIndex_;
        }
        /**
         * <code>optional int32 predefined_index = 2;</code>
         *
         * <pre>
         * Index of the predefined constant. If this field is present, the associated string is ignored
         * </pre>
         */
        public Builder setPredefinedIndex(int value) {
          bitField0_ |= 0x00000002;
          predefinedIndex_ = value;

          return this;
        }
        /**
         * <code>optional int32 predefined_index = 2;</code>
         *
         * <pre>
         * Index of the predefined constant. If this field is present, the associated string is ignored
         * </pre>
         */
        public Builder clearPredefinedIndex() {
          bitField0_ = (bitField0_ & ~0x00000002);
          predefinedIndex_ = 0;

          return this;
        }

        private Object string_ = "";
        /**
         * <code>optional string string = 6;</code>
         *
         * <pre>
         * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
         * </pre>
         */
        @Override
        public boolean hasString() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string string = 6;</code>
         *
         * <pre>
         * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
         * </pre>
         */
        @Override
        public String getString() {
          Object ref = string_;
          if (!(ref instanceof String)) {
            ByteString bs =
                (ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              string_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string string = 6;</code>
         *
         * <pre>
         * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
         * </pre>
         */
        @Override
        public ByteString
            getStringBytes() {
          Object ref = string_;
          if (ref instanceof String) {
            ByteString b =
                ByteString.copyFromUtf8(
                    (String) ref);
            string_ = b;
            return b;
          } else {
            return (ByteString) ref;
          }
        }
        /**
         * <code>optional string string = 6;</code>
         *
         * <pre>
         * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
         * </pre>
         */
        public Builder setString(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          string_ = value;

          return this;
        }
        /**
         * <code>optional string string = 6;</code>
         *
         * <pre>
         * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
         * </pre>
         */
        public Builder clearString() {
          bitField0_ = (bitField0_ & ~0x00000004);
          string_ = getDefaultInstance().getString();

          return this;
        }
        /**
         * <code>optional string string = 6;</code>
         *
         * <pre>
         * A string which should be used. If this field is present, both the associated string and the predefined string index are ignored
         * </pre>
         */
        public Builder setStringBytes(
            ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          string_ = value;

          return this;
        }

        private Operation operation_ = Operation.NONE;
        /**
         * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
         *
         * <pre>
         * Perform a described operation on the string
         * </pre>
         */
        @Override
        public boolean hasOperation() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
         *
         * <pre>
         * Perform a described operation on the string
         * </pre>
         */
        @Override
        public Operation getOperation() {
          return operation_;
        }
        /**
         * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
         *
         * <pre>
         * Perform a described operation on the string
         * </pre>
         */
        public Builder setOperation(Operation value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          operation_ = value;

          return this;
        }
        /**
         * <code>optional .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];</code>
         *
         * <pre>
         * Perform a described operation on the string
         * </pre>
         */
        public Builder clearOperation() {
          bitField0_ = (bitField0_ & ~0x00000008);
          operation_ = Operation.NONE;

          return this;
        }

        private java.util.List<Integer> substringIndex_ = java.util.Collections.emptyList();
        private void ensureSubstringIndexIsMutable() {
          if (!((bitField0_ & 0x00000010) == 0x00000010)) {
            substringIndex_ = new java.util.ArrayList<Integer>(substringIndex_);
            bitField0_ |= 0x00000010;
           }
        }
        /**
         * <code>repeated int32 substring_index = 4 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
         * and the second element as the end index.
         * If an operation is not NONE, it's applied _after_ this substring operation
         * </pre>
         */
        @Override
        public java.util.List<Integer>
            getSubstringIndexList() {
          return java.util.Collections.unmodifiableList(substringIndex_);
        }
        /**
         * <code>repeated int32 substring_index = 4 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
         * and the second element as the end index.
         * If an operation is not NONE, it's applied _after_ this substring operation
         * </pre>
         */
        @Override
        public int getSubstringIndexCount() {
          return substringIndex_.size();
        }
        /**
         * <code>repeated int32 substring_index = 4 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
         * and the second element as the end index.
         * If an operation is not NONE, it's applied _after_ this substring operation
         * </pre>
         */
        @Override
        public int getSubstringIndex(int index) {
          return substringIndex_.get(index);
        }
        /**
         * <code>repeated int32 substring_index = 4 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
         * and the second element as the end index.
         * If an operation is not NONE, it's applied _after_ this substring operation
         * </pre>
         */
        public Builder setSubstringIndex(
            int index, int value) {
          ensureSubstringIndexIsMutable();
          substringIndex_.set(index, value);

          return this;
        }
        /**
         * <code>repeated int32 substring_index = 4 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
         * and the second element as the end index.
         * If an operation is not NONE, it's applied _after_ this substring operation
         * </pre>
         */
        public Builder addSubstringIndex(int value) {
          ensureSubstringIndexIsMutable();
          substringIndex_.add(value);

          return this;
        }
        /**
         * <code>repeated int32 substring_index = 4 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
         * and the second element as the end index.
         * If an operation is not NONE, it's applied _after_ this substring operation
         * </pre>
         */
        public Builder addAllSubstringIndex(
            Iterable<? extends Integer> values) {
          ensureSubstringIndexIsMutable();
          AbstractMessageLite.Builder.addAll(
              values, substringIndex_);

          return this;
        }
        /**
         * <code>repeated int32 substring_index = 4 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "substring" operation must be performed with the first element of this list as the start index,
         * and the second element as the end index.
         * If an operation is not NONE, it's applied _after_ this substring operation
         * </pre>
         */
        public Builder clearSubstringIndex() {
          substringIndex_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);

          return this;
        }

        private java.util.List<Integer> replaceChar_ = java.util.Collections.emptyList();
        private void ensureReplaceCharIsMutable() {
          if (!((bitField0_ & 0x00000020) == 0x00000020)) {
            replaceChar_ = new java.util.ArrayList<Integer>(replaceChar_);
            bitField0_ |= 0x00000020;
           }
        }
        /**
         * <code>repeated int32 replace_char = 5 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
         * of the character to replace, and the second element as the code point of the replacement character
         * </pre>
         */
        @Override
        public java.util.List<Integer>
            getReplaceCharList() {
          return java.util.Collections.unmodifiableList(replaceChar_);
        }
        /**
         * <code>repeated int32 replace_char = 5 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
         * of the character to replace, and the second element as the code point of the replacement character
         * </pre>
         */
        @Override
        public int getReplaceCharCount() {
          return replaceChar_.size();
        }
        /**
         * <code>repeated int32 replace_char = 5 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
         * of the character to replace, and the second element as the code point of the replacement character
         * </pre>
         */
        @Override
        public int getReplaceChar(int index) {
          return replaceChar_.get(index);
        }
        /**
         * <code>repeated int32 replace_char = 5 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
         * of the character to replace, and the second element as the code point of the replacement character
         * </pre>
         */
        public Builder setReplaceChar(
            int index, int value) {
          ensureReplaceCharIsMutable();
          replaceChar_.set(index, value);

          return this;
        }
        /**
         * <code>repeated int32 replace_char = 5 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
         * of the character to replace, and the second element as the code point of the replacement character
         * </pre>
         */
        public Builder addReplaceChar(int value) {
          ensureReplaceCharIsMutable();
          replaceChar_.add(value);

          return this;
        }
        /**
         * <code>repeated int32 replace_char = 5 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
         * of the character to replace, and the second element as the code point of the replacement character
         * </pre>
         */
        public Builder addAllReplaceChar(
            Iterable<? extends Integer> values) {
          ensureReplaceCharIsMutable();
          AbstractMessageLite.Builder.addAll(
              values, replaceChar_);

          return this;
        }
        /**
         * <code>repeated int32 replace_char = 5 [packed = true];</code>
         *
         * <pre>
         * If this field is present, the "replaceAll" operation must be performed with the first element of this list as the code point
         * of the character to replace, and the second element as the code point of the replacement character
         * </pre>
         */
        public Builder clearReplaceChar() {
          replaceChar_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);

          return this;
        }

        // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record)
      }

      static {
        defaultInstance = new Record(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record)
    }

    public static final int RECORD_FIELD_NUMBER = 1;
    private java.util.List<Record> record_;
    /**
     * <code>repeated .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record record = 1;</code>
     */
    @Override
    public java.util.List<Record> getRecordList() {
      return record_;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record record = 1;</code>
     */
    public java.util.List<? extends RecordOrBuilder>
        getRecordOrBuilderList() {
      return record_;
    }
    /**
     * <code>repeated .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record record = 1;</code>
     */
    public RecordOrBuilder getRecordOrBuilder(
        int index) {
      return record_.get(index);
    }

    public static final int LOCAL_NAME_FIELD_NUMBER = 5;
    private java.util.List<Integer> localName_;
    /**
     * <code>repeated int32 local_name = 5 [packed = true];</code>
     *
     * <pre>
     * Indices of strings which are names of local classes or anonymous objects
     * </pre>
     */
    @Override
    public java.util.List<Integer>
        getLocalNameList() {
      return localName_;
    }
    private int localNameMemoizedSerializedSize = -1;

    private void initFields() {
      record_ = java.util.Collections.emptyList();
      localName_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < record_.size(); i++) {
        output.writeMessage(1, record_.get(i));
      }
      if (getLocalNameList().size() > 0) {
        output.writeRawVarint32(42);
        output.writeRawVarint32(localNameMemoizedSerializedSize);
      }
      for (int i = 0; i < localName_.size(); i++) {
        output.writeInt32NoTag(localName_.get(i));
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;

    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < record_.size(); i++) {
        size += CodedOutputStream
          .computeMessageSize(1, record_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < localName_.size(); i++) {
          dataSize += CodedOutputStream
            .computeInt32SizeNoTag(localName_.get(i));
        }
        size += dataSize;
        if (!getLocalNameList().isEmpty()) {
          size += 1;
          size += CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        localNameMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static StringTableTypes parseFrom(
        ByteString data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringTableTypes parseFrom(
        ByteString data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringTableTypes parseFrom(byte[] data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static StringTableTypes parseFrom(
        byte[] data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static StringTableTypes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringTableTypes parseFrom(
        java.io.InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static StringTableTypes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static StringTableTypes parseDelimitedFrom(
        java.io.InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static StringTableTypes parseFrom(
        CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static StringTableTypes parseFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(StringTableTypes prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.metadata.jvm.StringTableTypes}
     */
    public static final class Builder extends
        GeneratedMessageLite.Builder<
          StringTableTypes, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.metadata.jvm.StringTableTypes)
        StringTableTypesOrBuilder {
      // Construct using JvmProtoBuf.StringTableTypes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      @Override
      public Builder clear() {
        super.clear();
        record_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        localName_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
      public StringTableTypes getDefaultInstanceForType() {
        return StringTableTypes.getDefaultInstance();
      }

      @Override
      public StringTableTypes build() {
        StringTableTypes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public StringTableTypes buildPartial() {
        StringTableTypes result = new StringTableTypes(this);
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          record_ = java.util.Collections.unmodifiableList(record_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.record_ = record_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          localName_ = java.util.Collections.unmodifiableList(localName_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.localName_ = localName_;
        return result;
      }

      @Override
      public Builder mergeFrom(StringTableTypes other) {
        if (other == StringTableTypes.getDefaultInstance()) return this;
        if (!other.record_.isEmpty()) {
          if (record_.isEmpty()) {
            record_ = other.record_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRecordIsMutable();
            record_.addAll(other.record_);
          }

        }
        if (!other.localName_.isEmpty()) {
          if (localName_.isEmpty()) {
            localName_ = other.localName_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLocalNameIsMutable();
            localName_.addAll(other.localName_);
          }

        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        StringTableTypes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (InvalidProtocolBufferException e) {
          parsedMessage = (StringTableTypes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Record> record_ =
        java.util.Collections.emptyList();
      private void ensureRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          record_ = new java.util.ArrayList<Record>(record_);
          bitField0_ |= 0x00000001;
         }
      }

      /**
       * <code>repeated .org.jetbrains.kotlin.metadata.jvm.StringTableTypes.Record record = 1;</code>
       */
      @Override
      public java.util.List<Record> getRecordList() {
        return java.util.Collections.unmodifiableList(record_);
      }

      private java.util.List<Integer> localName_ = java.util.Collections.emptyList();
      private void ensureLocalNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          localName_ = new java.util.ArrayList<Integer>(localName_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 local_name = 5 [packed = true];</code>
       *
       * <pre>
       * Indices of strings which are names of local classes or anonymous objects
       * </pre>
       */
      @Override
      public java.util.List<Integer>
          getLocalNameList() {
        return java.util.Collections.unmodifiableList(localName_);
      }

      // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.metadata.jvm.StringTableTypes)
    }

    static {
      defaultInstance = new StringTableTypes(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.metadata.jvm.StringTableTypes)
  }

  public interface JvmMethodSignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.jetbrains.kotlin.metadata.jvm.JvmMethodSignature)
          MessageLiteOrBuilder {

    /**
     * <code>optional int32 name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional int32 name = 1;</code>
     */
    int getName();

    /**
     * <code>optional int32 desc = 2;</code>
     *
     * <pre>
     * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
     * </pre>
     */
    boolean hasDesc();
    /**
     * <code>optional int32 desc = 2;</code>
     *
     * <pre>
     * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
     * </pre>
     */
    int getDesc();
  }
  /**
   * Protobuf type {@code org.jetbrains.kotlin.metadata.jvm.JvmMethodSignature}
   */
  public static final class JvmMethodSignature extends
          GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:org.jetbrains.kotlin.metadata.jvm.JvmMethodSignature)
      JvmMethodSignatureOrBuilder {
    // Use JvmMethodSignature.newBuilder() to construct.
    private JvmMethodSignature(GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    @SuppressWarnings("UnusedVariable")
    private JvmMethodSignature(boolean noInit) {

      this.unknownFields = ByteString.EMPTY;
    }

    private static final JvmMethodSignature defaultInstance;
    public static JvmMethodSignature getDefaultInstance() {
      return defaultInstance;
    }

    @Override
    public JvmMethodSignature getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final ByteString unknownFields;
    private JvmMethodSignature(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      initFields();
      ByteString.Output unknownFieldsOutput =
          ByteString.newOutput();
      CodedOutputStream unknownFieldsCodedOutput =
          CodedOutputStream.newInstance(
              unknownFieldsOutput, 1);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              name_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              desc_ = input.readInt32();
              break;
            }
          }
        }
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static Parser<JvmMethodSignature> PARSER =
        new AbstractParser<JvmMethodSignature>() {
          @Override
      public JvmMethodSignature parsePartialFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws InvalidProtocolBufferException {
        return new JvmMethodSignature(input, extensionRegistry);
      }
    };

    @Override
    public Parser<JvmMethodSignature> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private int name_;
    /**
     * <code>optional int32 name = 1;</code>
     */
    @Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 name = 1;</code>
     */
    @Override
    public int getName() {
      return name_;
    }

    public static final int DESC_FIELD_NUMBER = 2;
    private int desc_;
    /**
     * <code>optional int32 desc = 2;</code>
     *
     * <pre>
     * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
     * </pre>
     */
    @Override
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 desc = 2;</code>
     *
     * <pre>
     * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
     * </pre>
     */
    @Override
    public int getDesc() {
      return desc_;
    }

    private void initFields() {
      name_ = 0;
      desc_ = 0;
    }
    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, desc_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;

    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += CodedOutputStream
          .computeInt32Size(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += CodedOutputStream
          .computeInt32Size(2, desc_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static JvmMethodSignature parseFrom(
        ByteString data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JvmMethodSignature parseFrom(
        ByteString data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JvmMethodSignature parseFrom(byte[] data)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static JvmMethodSignature parseFrom(
        byte[] data,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static JvmMethodSignature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JvmMethodSignature parseFrom(
        java.io.InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static JvmMethodSignature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static JvmMethodSignature parseDelimitedFrom(
        java.io.InputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static JvmMethodSignature parseFrom(
        CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static JvmMethodSignature parseFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(JvmMethodSignature prototype) {
      return newBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code org.jetbrains.kotlin.metadata.jvm.JvmMethodSignature}
     */
    public static final class Builder extends
        GeneratedMessageLite.Builder<
          JvmMethodSignature, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:org.jetbrains.kotlin.metadata.jvm.JvmMethodSignature)
        JvmMethodSignatureOrBuilder {
      // Construct using JvmProtoBuf.JvmMethodSignature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      @Override public Builder clear() {
        super.clear();
        name_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        desc_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      @Override
      public JvmMethodSignature getDefaultInstanceForType() {
        return JvmMethodSignature.getDefaultInstance();
      }

      @Override
      public JvmMethodSignature build() {
        JvmMethodSignature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public JvmMethodSignature buildPartial() {
        JvmMethodSignature result = new JvmMethodSignature(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.desc_ = desc_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      @Override
      public Builder mergeFrom(JvmMethodSignature other) {
        if (other == JvmMethodSignature.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDesc()) {
          setDesc(other.getDesc());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          CodedInputStream input,
          ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        JvmMethodSignature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (InvalidProtocolBufferException e) {
          parsedMessage = (JvmMethodSignature) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int name_ ;
      /**
       * <code>optional int32 name = 1;</code>
       */
      @Override
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 name = 1;</code>
       */
      @Override
      public int getName() {
        return name_;
      }
      /**
       * <code>optional int32 name = 1;</code>
       */
      public Builder setName(int value) {
        bitField0_ |= 0x00000001;
        name_ = value;

        return this;
      }
      /**
       * <code>optional int32 name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = 0;

        return this;
      }

      private int desc_ ;
      /**
       * <code>optional int32 desc = 2;</code>
       *
       * <pre>
       * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
       * </pre>
       */
      @Override
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 desc = 2;</code>
       *
       * <pre>
       * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
       * </pre>
       */
      @Override
      public int getDesc() {
        return desc_;
      }
      /**
       * <code>optional int32 desc = 2;</code>
       *
       * <pre>
       * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
       * </pre>
       */
      public Builder setDesc(int value) {
        bitField0_ |= 0x00000002;
        desc_ = value;

        return this;
      }
      /**
       * <code>optional int32 desc = 2;</code>
       *
       * <pre>
       * JVM descriptor of the method, e.g. '(Ljava/util/List;)[Ljava/lang/Object;'
       * </pre>
       */
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = 0;

        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.jetbrains.kotlin.metadata.jvm.JvmMethodSignature)
    }

    static {
      defaultInstance = new JvmMethodSignature(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.jetbrains.kotlin.metadata.jvm.JvmMethodSignature)
  }

  public static final int METHOD_SIGNATURE_FIELD_NUMBER = 100;
  /**
   * <code>extend .org.jetbrains.kotlin.metadata.Function { ... }</code>
   */
  public static final
    GeneratedMessageLite.GeneratedExtension<
            ProtoBuf.Function,
      JvmMethodSignature> methodSignature = GeneratedMessageLite
          .newSingularGeneratedExtension(
        ProtoBuf.Function.getDefaultInstance(),
        JvmMethodSignature.getDefaultInstance(),
        JvmMethodSignature.getDefaultInstance(),
        null,
        100,
        WireFormat.FieldType.MESSAGE,
        JvmMethodSignature.class);

  // @@protoc_insertion_point(outer_class_scope)
}