/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 11 11:09:59 GMT 2022
 */

package retrofit2;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.annotation.Annotation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import retrofit2.CompletableFutureCallAdapterFactory;
import retrofit2.Retrofit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CompletableFutureCallAdapterFactory_ESTest extends CompletableFutureCallAdapterFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CompletableFutureCallAdapterFactory completableFutureCallAdapterFactory0 = new CompletableFutureCallAdapterFactory();
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      Class<?> class0 = classLoader0.loadClass("retrofit2.CompletableFutureCallAdapterFactory");
      Annotation[] annotationArray0 = new Annotation[3];
      // Undeclared exception!
      try { 
        completableFutureCallAdapterFactory0.get(class0, annotationArray0, (Retrofit) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // okio/Sink
         //
         verifyException("retrofit2.CallAdapter$Factory", e);
      }
  }
}
