apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'com.vanniktech.maven.publish'
apply plugin: 'org.jetbrains.dokka'

dependencies {
  api projects.retrofit
  api projects.retrofitAdapters.sse.core
  api libs.kotlinx.coroutines
  compileOnly libs.findBugsAnnotations

  testImplementation libs.junit
  testImplementation libs.truth
  testImplementation libs.okhttp.mockwebserver
  testImplementation projects.retrofitConverters.scalars
  testImplementation projects.retrofitConverters.gson
}
